### ISSUE TITLE
Update vaccine eligibility content

### ISSUE THREAD

**Issue by dhcole** [newjersey/dol-eligibility-tool#24]
We have the following request from DOL:

> We just got the wording approved on using NJ Earned Sick Leave to get and receive the vaccine. We think this would be really helpful to add to the benefit eligibility tool.  Would you be able to make these updates? [Eligibility Tool Updates- 6-2.docx](https://github.com/newjersey/dol-eligibility-tool/files/6771198/Eligibility.Tool.Updates-.6-2.docx)

@stephan-schmidt: would you be able to help make these updates?

**Comment by stephan-schmidt** [comment]
Question about _New Logic_  task:  Is it J and K combined or is it either one of them that PUA appears?
